import java.lang.Exception;

public class TestException
{
	public static void main(String[] args) 
	{
		fun(args);
	}

	public static void fun(String[] s)
	{
		try
		{
			fun2(s);
		}
		catch (Exception e)
		{
			e.printStackTrace();
			return;
		}

		System.out.println("finish");
	}

	public static void fun2(String[] s)
		throws Exception
	{
			int a = Integer.parseInt(s[0]);
			int b = Integer.parseInt(s[1]);

			int temp = a / b;
			System.out.println(temp);
	}
}
